package com.doeist.Repository.TaskServices;

import com.doeist.Model.Task.Task;

import java.util.List;

public interface TaskRepository {

    List<Task> getAllMyTasks(String email);

    //  we want to display task id that is generated by us so
    // we could use it to get the task
    Task getTaskById(int id);

    //  we want to display task id that is generated by us so
    // we could use it to get the task
    void updateTask(int id ,String Description,boolean status,String note);

    void createTask(Task task);

    void deleteTask(int id);

    List<Task> getTasksSortedByDate();

    List<Task> getTaskSortedByPriority();


}
